# Generated by Django 4.2.4 on 2023-08-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_about_catagory_product_blacklistedtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='1', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.catagory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
        ),
    ]
